// This file is generated by Dao Nguyen Ninh and AI assistant
package com.github.warnastrophy.core.ui.dashboard

import com.github.warnastrophy.core.data.repository.MockContactRepository
import com.github.warnastrophy.core.domain.model.Contact
import com.github.warnastrophy.core.ui.features.dashboard.ContactCardState
import com.github.warnastrophy.core.ui.features.dashboard.DashboardEmergencyContactsStatefulViewModel
import junit.framework.TestCase
import kotlin.test.Test
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Before

@OptIn(ExperimentalCoroutinesApi::class)
class DashboardEmergencyContactsStatefulViewModelTest {
  private val testDispatcher = StandardTestDispatcher()

  private lateinit var mockRepository: MockContactRepository

  private lateinit var viewModel: DashboardEmergencyContactsStatefulViewModel

  private val mockContactList =
      listOf(
          Contact("1", "Alice", "+41567874201", "friend"),
          Contact("2", "Bob", "+41564812209", "work"))

  @Before
  fun setup() = runTest {
    Dispatchers.setMain(testDispatcher)

    mockRepository = MockContactRepository()

    mockContactList.forEach { contact -> mockRepository.addContact(contact = contact) }

    viewModel = DashboardEmergencyContactsStatefulViewModel(mockRepository)
  }

  @After
  fun tearDown() {
    Dispatchers.resetMain()
  }

  @Test
  fun `fetchContacts called on init should transition to Success on repository success`() =
      runTest {
        testScheduler.advanceUntilIdle()
        val expectedState = ContactCardState.Success(mockContactList)
        TestCase.assertEquals(expectedState, viewModel.contactsState.value)
      }

  @Test
  fun `fetchContacts called on init should transition to Error on repository failure`() = runTest {
    mockRepository.shouldThrowException = true
    viewModel.refreshUIStates()
    testScheduler.advanceUntilIdle()
    TestCase.assertEquals(ContactCardState.Error, viewModel.contactsState.value)
  }
}
